README.md

Team members added to the README

Readme modification with team members

---

docs/package-lock.json
docs/package.json
docs/src/05_building_block_view.adoc
package-lock.json

Level 1 Block View of the app:
- Diagram
- Motivation
- Black Boxes
- Interfaces

Block View Initial Approach

---

docs/src/06_runtime_view.adoc

Deleting <> on titles

---

docs/src/03_system_scope_and_context.adoc

First version of the point 3.2 of the documentatin of the project.

Point 3.2 of the documentation

---

docs/src/03_system_scope_and_context.adoc

First version of the point 3.2 of the documentation

Point 3.2 documentation

---

docs/src/01_introduction_and_goals.adoc

Documentation vira

---

docs/src/04_solution_strategy.adoc
docs/src/07_deployment_view.adoc

Deployment guide and infrastructure levels

Deployment view documentation

---

docs/src/07_deployment_view.adoc
package-lock.json

Deployment view diagrams

---

README.md

I moved the badges to the top.

Badges in ReadMe

---

wikidata_service/WikiDataTest/Program.cs
wikidata_service/WikiDataTest/Services/WikiDataService.cs

Adding cors middleware for allowing requests to itself

Adding CORS

---

docker-compose.yml
wikidata_service/WikiDataTest/Dockerfile

Changing containers' port to 7259

Changing API port

---

webapp/src/components/Game/Game.tsx
webapp/src/components/general/Nav.tsx
webapp/src/services/auth-service.ts
webapp/src/stores/playing-store.ts

Merging user scores

---

webapp/src/components/Game/Game.tsx

Minor fix in the record score that was duplicated when login out

Record bug fixed

---

sonar-project.properties

changes in sonar cloud to try to avoid errors

possible sonar cloud fix

---

README.md

Application and Documentation links were added for improving the README.

Added some links in the README

---

gatewayservice/openapi.yaml

OpenAPI for wikidata part

---

docs/src/04_solution_strategy.adoc
docs/src/07_deployment_view.adoc

Updating documentation section 4 and 7

Documentation sergiot

---

docker-compose.yml
gatewayservice/gateway-service.js
users/index.js
users/userservice/Dockerfile
wikidataservice/index.js

Changing users container port to 8003

Deploymeny issue

---

api/package-lock.json
webapp/src/components/Game/Answer.test.tsx
webapp/src/components/Game/Answer.tsx
webapp/src/components/Game/AnswerPanel.test.tsx
webapp/src/components/Game/AnswerPanel.tsx
webapp/src/components/Game/Countdown.test.tsx
webapp/src/components/Game/Counter.tsx
webapp/src/components/Game/Game.tsx
webapp/src/components/Game/GameOver.test.tsx
webapp/src/components/Game/GameOver.tsx
webapp/src/stores/playing-store.ts
wikidataservice/src/Services/QuestionGenerator.js

Table with the statistics of the last game added at the end.

Game statistic

---

webapp/src/components/Game/AnswerPanel.tsx
webapp/src/components/Game/Game.tsx
webapp/src/components/Game/GameOver.tsx
webapp/src/components/Game/Trivia/TriviaGame.tsx
webapp/src/components/Game/Trivia/TriviaQuestion.tsx
webapp/src/components/general/Home.test.tsx

The trivia game finishes when all 5 cheeses are owned and the game over screen is shown. During the normal game the current question number is shown instead of the score.

Front end improvements

---

webapp/src/components/leaderboard/LeaderBoard.tsx
webapp/src/components/leaderboard/TrivialRankingTable.tsx
webapp/src/index.css

Added a new leaderboard for the trivial ranking, and put the two leaderboards together in the same page but in different tabs

new leaderboard for trivial game 

---

gatewayservice/gateway-service.js
webapp/src/components/auth/AddUser.tsx
webapp/src/services/auth-service.ts

When registering with invalid credentials, the error message is shown

Registering error managment

---

.gitignore
users/index.js
users/package-lock.json
users/package.json

Login link to the database in mongo eliminated from the code

Security fix

---

webapp/src/components/Game/Trivia/trivia_service.ts
webapp/src/components/stats/StatsTable.test.tsx
webapp/src/components/stats/StatsTable.tsx
webapp/src/services/auth-service.test.tsx
webapp/src/services/question-service.ts

Few tests for the statistics table and authservice done.

Webapp tests

---

webapp/src/components/leaderboard/LeaderBoard.test.tsx
webapp/src/components/leaderboard/LeaderBoard.tsx

leaderboard tests

---

webapp/src/components/Game/Game.tsx
webapp/src/components/Game/Trivia/TriviaGame.tsx
webapp/src/components/auth/Login.tsx

initial fix approach for sonarcloud errors

sonarcloud fix
